"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("cypress-wait-until");
var logout_1 = require("./commands/logout");
var loginAs_1 = require("./commands/loginAs");
var acceptInviteFrom_1 = require("./commands/acceptInviteFrom");
var startGameWith_1 = require("./commands/startGameWith");
var startGameBetween_1 = require("./commands/startGameBetween");
var playMove_1 = require("./commands/playMove");
var playMoves_1 = require("./commands/playMoves");
var pegAt_1 = require("./commands/pegAt");
var currentPlayer_1 = require("./commands/currentPlayer");
var pegAtPosition_1 = require("./commands/pegAtPosition");
var confirmMove_1 = require("./commands/confirmMove");
var surrender_1 = require("./commands/surrender");
Cypress.Commands.add('loginAs', loginAs_1.loginAs);
Cypress.Commands.add('logout', logout_1.logout);
Cypress.Commands.add('acceptInviteFrom', acceptInviteFrom_1.acceptInviteFrom);
Cypress.Commands.add('startGameWith', startGameWith_1.startGameWith);
Cypress.Commands.add('startGameBetween', startGameBetween_1.startGameBetween);
Cypress.Commands.add('playMove', playMove_1.playMove);
Cypress.Commands.add('playMoves', playMoves_1.playMoves);
Cypress.Commands.add('confirmMove', confirmMove_1.confirmMove);
Cypress.Commands.add('surrender', surrender_1.surrender);
Cypress.Commands.add('pegAt', pegAt_1.pegAt);
Cypress.Commands.add('pegAtPosition', pegAtPosition_1.pegAtPosition);
Cypress.Commands.add('currentPlayer', currentPlayer_1.currentPlayer);
